/*
 * Copyright 2016 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package cb;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Computer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int cpu;

   public Computer()
   {
   }

   public int getCpu()
   {
      return this.cpu;
   }

   public void setCpu(int cpu)
   {
      this.cpu = cpu;
   }

   public Computer(int cpu)
   {
      this.cpu = cpu;
   }

}