image:https://jenkins-kieci.rhcloud.com/buildStatus/icon?job=optaplanner-wb["Build Status", link="https://jenkins-kieci.rhcloud.com/job/optaplanner-wb"]

== Quick development start

To build and run from source:

----
$ mvn clean install -DskipTests
$ cd optaplanner-wb-webapp
$ mvn clean gwt:run
----

To develop with IntelliJ IDEA, Eclipse or NetBeans, open the root `pom.xml` as a new project
and configure a _Run/Debug configuration_ like this:

* Type: GWT configuration
* Module: `optaplanner-wb-webapp`
* User Super Dev mode: `yes`
* GWT Modules to load: `...FastCompiledOptaPlannerWorkbench`
* VM options: `-Xmx2g -XX:MaxPermSize=512m -Xms1g -Xss1M -XX:CompileThreshold=7000 -Derrai.jboss.home=/.../optaplanner-wb/optaplanner-wb-webapp/target/wildfly-8.1.0.Final/` (replace `/.../optaplanner-wb/` with your clone directory path)
* Dev Mode parameters: `-server org.jboss.errai.cdi.server.gwt.EmbeddedWildFlyLauncher`
* Environment variables: (none)

== Developing Drools, OptaPlanner and jBPM

*If you want to build or contribute to a droolsjbpm project, https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/blob/master/README.md[read this document].*

*It will save you and us a lot of time by setting up your development environment correctly.*
It solves all known pitfalls that can disrupt your development.
It also describes all guidelines, tips and tricks.
If you want your pull requests (or patches) to be merged into master, please respect those guidelines.
